#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 25 19:29:53 2024

@author: iwan
"""

import serial

ser = serial.Serial('/dev/serial0', 115200)
ser.write(b'Hello Raspberry PI')
ser.close()